-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 20:25:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema posSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posSystem` DEFAULT CHARACTER SET utf8 ;
USE `posSystem` ;

-- -----------------------------------------------------
-- Table `posSystem`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`customer` (
  `cusId` INT NOT NULL AUTO_INCREMENT,
  `cusTitle` VARCHAR(45) NOT NULL,
  `cusName` VARCHAR(255) NOT NULL,
  `cusCode` VARCHAR(45) NULL,
  `cusAddress` VARCHAR(255) NOT NULL,
  `cusPhone` VARCHAR(255) NOT NULL,
  `cusEmail` VARCHAR(255) NOT NULL,
  `cusNIC` VARCHAR(45) NOT NULL,
  `cusCity` VARCHAR(45) NOT NULL,
  `cusJob` VARCHAR(45) NOT NULL,
  `cusCompany` VARCHAR(100) NOT NULL,
  `cusWorkPlaceTP` VARCHAR(45) NOT NULL,
  `cusWorkPlaceAddress` VARCHAR(45) NOT NULL,
  `cusPoints` VARCHAR(45) NOT NULL,
  `cusStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`category` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(255) NOT NULL,
  `categoryType` VARCHAR(100) NOT NULL,
  `categoryStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`products` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(255) NOT NULL,
  `productCode` VARCHAR(45) NOT NULL,
  `productUnit` VARCHAR(255) NOT NULL,
  `productDiscount` FLOAT NULL,
  `productBuyingPrice` INT NOT NULL,
  `productSellingPrice` INT NOT NULL,
  `productWarranty` VARCHAR(100) NULL,
  `productProfit` FLOAT NOT NULL,
  `productEmi` VARCHAR(255) NULL,
  `productDescription` VARCHAR(255) NULL,
  `productImage` VARCHAR(255) NULL,
  `productStatus` VARCHAR(45) NOT NULL,
  `category_categoryId` INT NOT NULL,
  PRIMARY KEY (`productId`),
  INDEX `fk_products_category_idx` (`category_categoryId` ASC),
  CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_categoryId`)
    REFERENCES `posSystem`.`category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`supplier` (
  `supplierId` INT NOT NULL AUTO_INCREMENT,
  `supplierName` VARCHAR(45) NOT NULL,
  `supplierAddress` VARCHAR(255) NOT NULL,
  `supplierNic` VARCHAR(45) NOT NULL,
  `supplierEmail` VARCHAR(45) NOT NULL,
  `supplierTP` VARCHAR(45) NOT NULL,
  `supplierSecondTP` VARCHAR(45) NOT NULL,
  `supplierStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplierId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`store` (
  `storeId` INT NOT NULL AUTO_INCREMENT,
  `storeName` VARCHAR(45) NOT NULL,
  `storeAddress` VARCHAR(255) NOT NULL,
  `storeStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`storeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`stock` (
  `stockId` INT NOT NULL AUTO_INCREMENT,
  `stockName` VARCHAR(255) NOT NULL,
  `stockdate` DATETIME NOT NULL,
  `billImage` VARCHAR(255) NULL,
  `stockPrice` FLOAT NOT NULL,
  `due` FLOAT NOT NULL,
  `vat` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `stockQty` INT NOT NULL,
  `mfd` DATE NULL,
  `exp` DATE NULL,
  `cashAmount` FLOAT NULL,
  `chequeAmount` FLOAT NULL,
  `stockDescription` VARCHAR(255) NULL,
  `stockStatus` VARCHAR(45) NOT NULL,
  `products_productId` INT NOT NULL,
  `supplier_supplierId` INT NOT NULL,
  `store_storeId` INT NOT NULL,
  `category_categoryId` INT NOT NULL,
  PRIMARY KEY (`stockId`),
  INDEX `fk_stock_products1_idx` (`products_productId` ASC),
  INDEX `fk_stock_supplier1_idx` (`supplier_supplierId` ASC),
  INDEX `fk_stock_store1_idx` (`store_storeId` ASC),
  INDEX `fk_stock_category1_idx` (`category_categoryId` ASC),
  CONSTRAINT `fk_stock_products1`
    FOREIGN KEY (`products_productId`)
    REFERENCES `posSystem`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_supplier1`
    FOREIGN KEY (`supplier_supplierId`)
    REFERENCES `posSystem`.`supplier` (`supplierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_store1`
    FOREIGN KEY (`store_storeId`)
    REFERENCES `posSystem`.`store` (`storeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_category1`
    FOREIGN KEY (`category_categoryId`)
    REFERENCES `posSystem`.`category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`invoice` (
  `invoiceId` INT NOT NULL AUTO_INCREMENT,
  `invoiceNo` VARCHAR(45) NOT NULL,
  `invoiceDate` DATETIME NOT NULL,
  `totalAmount` FLOAT NOT NULL,
  `invoiceQty` INT NOT NULL,
  `customer_cusId` INT NOT NULL,
  `products_productId` INT NOT NULL,
  `stock_stockId` INT NOT NULL,
  PRIMARY KEY (`invoiceId`),
  INDEX `fk_invoice_customer1_idx` (`customer_cusId` ASC),
  INDEX `fk_invoice_products1_idx` (`products_productId` ASC),
  INDEX `fk_invoice_stock1_idx` (`stock_stockId` ASC),
  CONSTRAINT `fk_invoice_customer1`
    FOREIGN KEY (`customer_cusId`)
    REFERENCES `posSystem`.`customer` (`cusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_products1`
    FOREIGN KEY (`products_productId`)
    REFERENCES `posSystem`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_stock1`
    FOREIGN KEY (`stock_stockId`)
    REFERENCES `posSystem`.`stock` (`stockId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userTitle` VARCHAR(45) NOT NULL,
  `userFullName` VARCHAR(100) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(255) NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userNIC` VARCHAR(45) NOT NULL,
  `userSecondTP` VARCHAR(45) NULL,
  `userTP` VARCHAR(45) NOT NULL,
  `userAddress` VARCHAR(255) NOT NULL,
  `userImage` VARCHAR(255) NULL,
  `userStatus` VARCHAR(45) NOT NULL,
  `store_storeId` INT NOT NULL,
  `is_hidden` TINYINT(1) NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_user_store1_idx` (`store_storeId` ASC),
  CONSTRAINT `fk_user_store1`
    FOREIGN KEY (`store_storeId`)
    REFERENCES `posSystem`.`store` (`storeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`transaction` (
  `transactionId` INT NOT NULL AUTO_INCREMENT,
  `transactionType` VARCHAR(255) NOT NULL,
  `price` VARCHAR(100) NOT NULL,
  `discount` FLOAT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `note` VARCHAR(255) NULL,
  `paid` FLOAT NULL,
  `due` FLOAT NULL,
  `invoice_invoiceId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  PRIMARY KEY (`transactionId`),
  INDEX `fk_transaction_invoice1_idx` (`invoice_invoiceId` ASC),
  INDEX `fk_transaction_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_transaction_invoice1`
    FOREIGN KEY (`invoice_invoiceId`)
    REFERENCES `posSystem`.`invoice` (`invoiceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `posSystem`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`returnItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`returnItems` (
  `returnItemId` INT NOT NULL AUTO_INCREMENT,
  `returnItemType` VARCHAR(45) NOT NULL,
  `returnItemDate` DATETIME NOT NULL,
  `returnQty` INT NULL,
  `returnNote` VARCHAR(45) NULL,
  `products_productId` INT NOT NULL,
  `store_storeId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  `invoice_invoiceId` INT NOT NULL,
  `customer_cusId` INT NOT NULL,
  PRIMARY KEY (`returnItemId`),
  INDEX `fk_return_products1_idx` (`products_productId` ASC),
  INDEX `fk_return_store1_idx` (`store_storeId` ASC),
  INDEX `fk_return_user1_idx` (`user_userId` ASC),
  INDEX `fk_return_invoice1_idx` (`invoice_invoiceId` ASC),
  INDEX `fk_returnItems_customer1_idx` (`customer_cusId` ASC),
  CONSTRAINT `fk_return_products1`
    FOREIGN KEY (`products_productId`)
    REFERENCES `posSystem`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_return_store1`
    FOREIGN KEY (`store_storeId`)
    REFERENCES `posSystem`.`store` (`storeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_return_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `posSystem`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_return_invoice1`
    FOREIGN KEY (`invoice_invoiceId`)
    REFERENCES `posSystem`.`invoice` (`invoiceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_returnItems_customer1`
    FOREIGN KEY (`customer_cusId`)
    REFERENCES `posSystem`.`customer` (`cusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`rentalInvoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`rentalInvoice` (
  `rentalInvoiceId` INT NOT NULL AUTO_INCREMENT,
  `rentalInvoiceDate` VARCHAR(45) NOT NULL,
  `rentalInvoiceTotalAMount` VARCHAR(100) NOT NULL,
  `rentalInvoiceAdvancePayment` VARCHAR(100) NOT NULL,
  `rentalInvoiceNote` VARCHAR(255) NOT NULL,
  `customer_cusId` INT NOT NULL,
  `products_productId` INT NOT NULL,
  PRIMARY KEY (`rentalInvoiceId`),
  INDEX `fk_rentalInvoice_customer1_idx` (`customer_cusId` ASC),
  INDEX `fk_rentalInvoice_products1_idx` (`products_productId` ASC),
  CONSTRAINT `fk_rentalInvoice_customer1`
    FOREIGN KEY (`customer_cusId`)
    REFERENCES `posSystem`.`customer` (`cusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentalInvoice_products1`
    FOREIGN KEY (`products_productId`)
    REFERENCES `posSystem`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`expensesCat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`expensesCat` (
  `expensesCatId` INT NOT NULL AUTO_INCREMENT,
  `expensesCatName` VARCHAR(45) NOT NULL,
  `expensesCatType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`expensesCatId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`expenses` (
  `expensesId` INT NOT NULL AUTO_INCREMENT,
  `expensesRef` VARCHAR(45) NOT NULL,
  `expensesNote` VARCHAR(255) NOT NULL,
  `expensesAmount` VARCHAR(45) NOT NULL,
  `expensesDate` VARCHAR(45) NOT NULL,
  `expensesImage` VARCHAR(255) NOT NULL,
  `expensesCat_expensesCatId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  PRIMARY KEY (`expensesId`),
  INDEX `fk_Expenses_expensesCat1_idx` (`expensesCat_expensesCatId` ASC),
  INDEX `fk_Expenses_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_Expenses_expensesCat1`
    FOREIGN KEY (`expensesCat_expensesCatId`)
    REFERENCES `posSystem`.`expensesCat` (`expensesCatId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Expenses_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `posSystem`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posSystem`.`stockHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posSystem`.`stockHistory` (
  `stockHistoryId` INT NOT NULL AUTO_INCREMENT,
  `stockHistoryQty` INT NOT NULL,
  `stock_stockId` INT NOT NULL,
  `products_productId` INT NOT NULL,
  PRIMARY KEY (`stockHistoryId`),
  INDEX `fk_stockHistory_stock1_idx` (`stock_stockId` ASC),
  INDEX `fk_stockHistory_products1_idx` (`products_productId` ASC),
  CONSTRAINT `fk_stockHistory_stock1`
    FOREIGN KEY (`stock_stockId`)
    REFERENCES `posSystem`.`stock` (`stockId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stockHistory_products1`
    FOREIGN KEY (`products_productId`)
    REFERENCES `posSystem`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
